### ISSUE TITLE
Complete committee details (usernames, photos, blurbs)

### ISSUE THREAD

**Issue by Aterfax** [SLUGSoc/website-old#49] opened 2018-09-08 21:33 UTC
Without pictures of committee members it is not possible for a member to find a specific member of the committee.

No explanation of each role is given.

How do users contact a specific committee member if they do not know their face or which committee role they need to contact?

**Comment by Aterfax** [comment] 2018-09-08 21:34
Text offsets for boxes are also not fixed indep of filled in social media profile buttons resulting in the following:

![image](https://user-images.githubusercontent.com/8648058/45258826-53bbbe00-b3b7-11e8-9be0-73f386a69192.png)

![image](https://user-images.githubusercontent.com/8648058/45258828-57e7db80-b3b7-11e8-81fd-5f958fa24c70.png)

**Comment by Aterfax** [comment] 2018-09-08 21:35
User feedback:

> Why is tech so far down? If you have a problem they're likely to be one of the people you most need to contact

**Comment by boardfish** [comment] 2018-09-08 21:57
This should be broken into several issues. I'll use this one for filling out committee details (inc. photo). As for the username thing, I think I'll just mute the color on it to draw less attention to it.

**Comment by boardfish** [comment] 2018-09-08 22:01
I'm also not going to leave an odd number of columns with a bunch of empty space at the side. That's an intentional design decision.

**Comment by boardfish** [comment] 2018-09-08 22:02
Closed as duplicate of #1.

**Closed as completed by boardfish** 2018-09-08 22:02 UTC
